//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMovie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorrorMoviesEntities : DbContext
    {
        public HorrorMoviesEntities()
            : base("name=HorrorMoviesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesstoken> accesstokens { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<movy> movies { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
